# Generated by Django 4.0.2 on 2022-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('quizcode', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, null=True)),
                ('wrongansw1', models.CharField(max_length=200, null=True)),
                ('wrongansw2', models.CharField(max_length=200, null=True)),
                ('wrongansw3', models.CharField(max_length=200, null=True)),
                ('correctansw', models.CharField(max_length=200, null=True)),
                ('qquizcode', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
