# Generated by Django 4.0 on 2022-03-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizdata',
            name='wrongansw4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
