# Generated by Django 4.0.2 on 2022-03-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQAttemptStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('rollno', models.CharField(max_length=200, null=True)),
                ('quizcode', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
